### ISSUE TITLE
模型如何转换到pb格式

### ISSUE THREAD

**Issue by rush9838465** [bubbliiiing/yolov4-keras#18]
我想把训练好的模型转换到tf-serving上使用, pb格式的,请问有什么代码可以参考的吗? 谢谢~

**Comment by bubbliiiing** [comment]
我没有转过，百度上应该有很多资料吧

**Comment by rush9838465** [comment]
我这边转换成功了, 测试在TITAN V 上608*608 速度在38ms, 416 在24ms, 感觉和darknet版本有差距.你知道什么原因吗
