### ISSUE TITLE
怎么开启gpu训练呢

### ISSUE THREAD

**Issue by wyw14** [bubbliiiing/yolov4-keras#2]

**Comment by lincuncuncaogoudan** [comment]
pip install tensorflow-gpu==1.13.1 
keras会自动调用gpu

**Comment by wyw14** [comment]
我的cuda是10.2，cudnn是10.1版本如果用tf-gpu1.13.1的话会报错版本要怎么调整呢。

**Comment by lincuncuncaogoudan** [comment]
10.2太新了，建议降级，cuda版本和tesorflow版本有对应表，你可以去查一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wyw14"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月22日(星期五) 中午11:02
收件人:&nbsp;"bubbliiiing/yolov4-keras"<yolov4-keras@noreply.github.com&gt;;
抄送:&nbsp;"huhongyang"<997739480@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [bubbliiiing/yolov4-keras] 怎么开启gpu训练呢 (#2)





 
我的cuda是10.2，cudnn是10.1版本如果用tf-gpu1.13.1的话会报错版本要怎么调整呢。

**Comment by cerulean2014** [comment]
+1，用10.0的cuda和最新适配10.0的cudnn就行，然后我在代码中间加了：
config = tf.ConfigProto()
config.gpu_options.allocator_type = 'BFC' #A "Best-fit with coalescing" algorithm, simplified from a version of dlmalloc.
config.gpu_options.per_process_gpu_memory_fraction = 0.7
config.gpu_options.allow_growth = True
set_session(tf.Session(config=config)) 

避免显存不够用报错

**Comment by wyw14** [comment]
好的谢谢。tensorflow有什么比较好的教程吗我看tensor对象中的变量怎么那么多啊。

**Comment by bubbliiiing** [comment]
我有对应的环境配置教程噢，而且这个库主要是keras实现，不是tf实现

**Comment by leozicai** [comment]
其实cuda10.2也可以用的，不用退版本。直接在你的anaconda化境里面 conda install cudatoolkit=10.0 即可。
具体在https://blog.csdn.net/qq_28193019/article/details/103146116
