### ISSUE TITLE
关于每张图检测数量最大为20的问题

### ISSUE THREAD

**Issue by sunRaisingEast** [bubbliiiing/yolov4-keras#25]
我用wider face数据集在您的v4上训练，分类也改成了只有人脸1类，训练50个epoch后做测试，运行get_gt_txt，得到的ground-truth中有很多图片中的人脸数量都超过20个，但运行get_dr_txt.py后，所有的预测结果中，在每张人脸图片标出来的人脸最多都不超过20个，这是什么原因，谢谢！

**Comment by sunRaisingEast** [comment]
是不是在代码中什么地方有设置？不太清楚，谢谢老师。

**Comment by vincent9619** [comment]
您好，我也遇到了这个问题，可否赐教您是如何解决的？谢谢！

**Comment by bubbliiiing** [comment]
可以修改yolo_eval里面的最大数量

**Comment by vincent9619** [comment]
感谢老师！
