### ISSUE TITLE
检测时box的数量是否设置了上限

### ISSUE THREAD

**Issue by vincent9619** [bubbliiiing/yolov4-keras#29]
老师您好，我用自己的训练集（单class）训练完成后进行测试时发现每张图片预测的数量上限都在20，我找了一下yolo.py并没有发现有相关的设置，请问这个上限是在哪里设置的，谢谢！

**Comment by bubbliiiing** [comment]
应该在yolo_eval里面

**Comment by vincent9619** [comment]
找到了，非常感谢老师！
