### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by leader402** [bubbliiiing/yolov4-keras#31]
大兄弟，哈哈。
1.我的数据命名都是从1自增的，用voc2yoyo4.py生成的train.txt中数字却不是自增的。这是不是无法和图片一一对应了。
2.运行voc_annotation.py时，显示UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 96: illegal multibyte sequence；这个我查了都是从生成的文件中读数据，也没发现有非法字符。这是怎么回事呀

**Comment by leader402** [comment]
这个还是没解决。o(╥﹏╥)o

**Comment by bubbliiiing** [comment]
你是否由中文字，可以添加一个以 utf-8方式打开

**Comment by leader402** [comment]
谢谢up，是因为目录有中文，设置encoding后可以了。
