### ISSUE TITLE
训练时loss值为nan

### ISSUE THREAD

**Issue by myleosu** [bubbliiiing/yolov4-keras#36]
CUDA：10.0.130
系统：Ubuntu 16.04
tensorflow: 1.13
batchsize：8
问题：第一个eporch时loss就出现nan，采用COCO数据集，检测的目标物为：车辆、红绿灯、行人。
![QQ截图20200806194946](https://user-images.githubusercontent.com/33693783/89529048-a52c8c00-d81e-11ea-9074-ff439c5fa254.jpg)

**Comment by myleosu** [comment]
数据集大小：5.9w张图片，train:val = 9:1

**Comment by rongrong9005** [comment]
调低学习率看看

**Comment by bubbliiiing** [comment]
有些时候会这样，重新开始一遍就好了，不过已经很少出现了，我感觉是cspdarknet53的问题……

**Comment by myleosu** [comment]
把Cosine_scheduler 设为 True，开启预热期就不会出现nan了，感谢博主优秀的代码。
