### ISSUE TITLE
voc07_test mAP

### ISSUE THREAD

**Issue by MiniLisaBear** [bubbliiiing/yolov4-keras#55]
您好，我用您的yolo4_voc_weights.h5模型在voc07_test数据集上运行，最终得到mAP为64.4，而您给出的mAP是84，请问您知道是什么原因吗？

**Comment by bubbliiiing** [comment]
我不知道，你是怎么做的…

**Comment by MiniLisaBear** [comment]
我通过yolo.py生成07_test数据的结果txt文件，然后通过main.py得到mAP


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bubbliiiing/yolov4-keras"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月26日(星期二) 中午1:28
收件人:&nbsp;"bubbliiiing/yolov4-keras"<yolov4-keras@noreply.github.com&gt;;
抄送:&nbsp;"2511415342"<2511415342@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bubbliiiing/yolov4-keras] voc07_test mAP (#55)





 
我不知道，你是怎么做的…

**Comment by MiniLisaBear** [comment]
这是我得到的类别的AP值


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bubbliiiing/yolov4-keras"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月26日(星期二) 中午1:28
收件人:&nbsp;"bubbliiiing/yolov4-keras"<yolov4-keras@noreply.github.com&gt;;
抄送:&nbsp;"2511415342"<2511415342@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bubbliiiing/yolov4-keras] voc07_test mAP (#55)





 
我不知道，你是怎么做的…

**Comment by bubbliiiing** [comment]
我没看到你的图还是啥。。你在B站私信吧

**Comment by MiniLisaBear** [comment]
您好，我已经在b站私信了，期待您的回复，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bubbliiiing/yolov4-keras"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月26日(星期二) 下午4:05
收件人:&nbsp;"bubbliiiing/yolov4-keras"<yolov4-keras@noreply.github.com&gt;;
抄送:&nbsp;"2511415342"<2511415342@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bubbliiiing/yolov4-keras] voc07_test mAP (#55)





 
我没看到你的图还是啥。。你在B站私信吧
