### ISSUE TITLE
请问一下，loss在第一个epoch的时候出现nan

### ISSUE THREAD

**Issue by mengmeng0320** [bubbliiiing/yolov4-keras#56]
训练时，loss在第一个epoch出现nan，这种情况很随机，有时候出现nan，有时候又可以一直收敛到loss下降到20一下，检查了数据没有问题，不太清楚问题出在哪，望提点一二

699/984 [====================>.........] - ETA: 4:42 - loss: 718.5894mf:[16]
mf:[16]
loss: [nan][nan][nan][nan][9747]
loss: [nan][nan][nan][nan][25992]
loss: [nan][nan][nan][nan][86640]
700/984 [====================>.........] - ETA: 4:41 - loss: nan     mf:[16]
mf:[16]
loss: [nan][nan][nan][nan][7581]
loss: [nan][nan][nan][nan][30324]
loss: [nan][nan][nan][nan][69312]
701/984 [====================>.........] - ETA: 4:40 - loss: nanmf:[16]
mf:[16]
loss: [nan][nan][nan][nan][5415]
loss: [nan][nan][nan][nan][21660]
loss: [nan][nan][nan][nan][34656]

**Comment by mengmeng0320** [comment]
@bubbliiiing

**Comment by bubbliiiing** [comment]
刚开始的学习率较大，很容易爆炸变成nan，你可以稍微调小学习率或者多尝试几次，一般三个epoch之后就不会有nan了

**Comment by bubbliiiing** [comment]
不过你可以下新代码

**Comment by mengmeng0320** [comment]
嗯嗯，好的，之前试过调小学习率也没不行，已经下载新的代码，没有出现nan的问题了，谢谢啦~

**Comment by mengmeng0320** [comment]
> 刚开始的学习率较大，很容易爆炸变成nan，你可以稍微调小学习率或者多尝试几次，一般三个epoch之后就不会有nan了

试了调小学习率，还是会出现nan，不太明白什么原因

**Comment by mengmeng0320** [comment]
> 不过你可以下新代码

新代码没有出现这个问题了，谢谢~

**Comment by mengmeng0320** [comment]
打扰啦，我现在又有一个新的问题，想要批测试图片，在输入的时候是batch形式（batch_size, 608，608，3）的，但是预测出框的时候box_xy, box_wh, box_confidence, box_class_probs = yolo_head(feats,
         anchors, num_classes, input_shape)     boxes = yolo_correct_boxes(box_xy, box_wh, input_shape, image_shape)
    boxes = K.reshape(boxes, [-1, 4])#reshape,将不同网格的值转换为框的列表。即（?,13,13,3,4）->(?,4)  ？：框的数目

**Comment by mengmeng0320** [comment]
打扰啦，我现在想要批测试，一个batch多张图去检测，但是在得到检测框的时候他的维度不包含batch维度，请问要怎么处理呀，尝试过reshape保存维度，但是因为是多尺度，reshape不可以转换成不固定维度报错
box_xy, box_wh, box_confidence, box_class_probs = yolo_head(feats,
         anchors, num_classes, input_shape)     boxes = yolo_correct_boxes(box_xy, box_wh, input_shape, image_shape)
boxes = K.reshape(boxes, [-1, 4]) 这里reshape完box就没有batch的维度了
@bubbliiiing

**Comment by bubbliiiing** [comment]
这个代码不支持多BATCH的预测……你可以去了K.reshape(boxes, [-1, 4])，然后对batch循环进行非极大抑制

**Comment by mengmeng0320** [comment]
> 这个代码不支持多BATCH的预测……你可以去了K.reshape(boxes, [-1, 4])，然后对batch循环进行非极大抑制

嗯嗯，了解啦，谢谢~
