### ISSUE TITLE
循环读取文件夹图片

### ISSUE THREAD

**Issue by carywangwang** [bubbliiiing/yolov4-keras#64]
您好，我想请问下我写的这个遍历读取文件夹中的图片为什么是一直报错的？

while True:
    
    path='E:\\anaconda1\\date\\its'
    imagelist=os.listdir(path)
    try:        
        for imgname in imagelist: 
            image = Image.open(path+imgname)
    except:
        print('Open Error! Try again!')
        continue
    else:
        r_image = yolo.detect_image(image)
        r_image.show()

**Comment by bubbliiiing** [comment]
少了一个\号
